### ISSUE TITLE
using sendImageBuffer utility will cause the rpc to be called twice 

### ISSUE THREAD

**Issue by hamidzr** [NetsBlox/NetsBlox#1475] opened 2017-09-01 21:38 UTC
```
netsblox~$   netsblox:rpc-manager:info Received request to Pixabay for getImage (from _netsblox1504297238459) +16s
  netsblox:rpc-manager:log calling Pixabay.getImage("https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png") +1ms
  netsblox:rpc-manager:info Received request to Pixabay for getImage (from _netsblox1504297238459) +29ms
  netsblox:rpc-manager:log calling Pixabay.getImage("https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png") +0ms

```

**Comment by brollb** [comment] 2018-01-17 17:44
I think this was actually caused by how the images were handled on the client. This is fixed as of #1823

**Closed by brollb** 2018-01-17 17:44 UTC
Labels: amazon, bug
